<a href="https://colab.research.google.com/github/gabrielwithappy/pytorch_references/blob/main/Pytorch_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
import numpy as np

# Pytorch 기본

## Tensor 생성

In [9]:
data = [[3,5],[10,5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [10]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

## GPU에 변수 올리기

In [11]:
data = [[3,5],[10,5]]
x_data = torch.tensor(data)
x_data.device


device(type='cpu')

In [12]:
if torch.cuda.is_available():
  x_data_cuda = x_data.to('cuda')
  x_data_cuda.device

## Torch View Hangling

In [13]:
tensor_ex = torch.rand(size=(2, 3, 2))
tensor_ex

tensor([[[0.1276, 0.4262],
         [0.1710, 0.2664],
         [0.2366, 0.6438]],

        [[0.8062, 0.5459],
         [0.5875, 0.9806],
         [0.4418, 0.1467]]])

In [14]:
tensor_ex.view([-1,6])

tensor([[0.1276, 0.4262, 0.1710, 0.2664, 0.2366, 0.6438],
        [0.8062, 0.5459, 0.5875, 0.9806, 0.4418, 0.1467]])

In [15]:
tensor_ex.reshape([-1,6])

tensor([[0.1276, 0.4262, 0.1710, 0.2664, 0.2366, 0.6438],
        [0.8062, 0.5459, 0.5875, 0.9806, 0.4418, 0.1467]])

## Difference btw view and reshape

In [16]:
a = torch.zeros(3,2)
b = a.view(2,3)
a.fill_(1)
# view를 사용하면 a의 메모리 주소를 이용하여 변경하기 때문에 a를 변경하면 view를 통해 변경한 b도 변경된다.

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [17]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [18]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## squeeze, unsqueeze

In [19]:
tensor_ex = torch.rand(size=(2,1,2,3,4,5))
print(tensor_ex.shape)
tensor_ex = tensor_ex.squeeze()
print(tensor_ex.shape)

torch.Size([2, 1, 2, 3, 4, 5])
torch.Size([2, 2, 3, 4, 5])


In [20]:
tensor_ex = torch.rand(size=(2,2))
print(tensor_ex.unsqueeze(0).shape)
print(tensor_ex.unsqueeze(1).shape)
print(tensor_ex.unsqueeze(2).shape)


torch.Size([1, 2, 2])
torch.Size([2, 1, 2])
torch.Size([2, 2, 1])


## Tensor Operation

In [21]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

## matrix multiplication

In [22]:
mat_result = t1.matmul(t2)
mat_result

tensor([[ 60.,  70.],
        [160., 195.]])

In [25]:
## matmul 과 mul의 차이점
# matmul은 broadcasting을 지원한다.
# mul은 element-wise 곱셈
a = torch.rand(5,2,3)
b = torch.rand(3)


## Tensor vs Parameter

In [26]:
import torch
from torch import nn
from torch import Tensor

In [27]:
class MyLinear(nn.Module):
  def __init__(self, in_features, out_features, bias=True):
    super().__init__()
    self.in_features = in_features
    self.out_features = out_features
    
    self.weights = nn.Parameter(
        torch.randn(in_features, out_features)
    )

    self.bias = nn.Parameter(torch.randn(out_features))

  def forward(self, x:Tensor):
    return x @ self.weights + self.bias

In [28]:
x = torch.randn(5,7)

In [29]:
x.shape

torch.Size([5, 7])

In [30]:
layer = MyLinear(7,12)
layer(x).shape

torch.Size([5, 12])

In [31]:
for value in layer.parameters():
  print(value)

Parameter containing:
tensor([[ 0.4578,  1.8471,  0.4252,  1.2517, -0.9735,  0.8305, -1.2481, -0.3753,
         -0.9960,  0.2928,  1.0834,  1.5424],
        [-1.5911,  1.0194, -1.3189, -2.2552,  0.0674,  0.4391,  1.1063, -0.8333,
          0.7412,  1.4215, -0.1255,  0.6890],
        [-0.5559,  0.3737, -0.3189,  1.5434, -1.3780,  0.0399,  0.8203, -1.3079,
         -0.7008, -0.4337, -0.3531, -0.2104],
        [-1.0666,  1.6718, -0.3773,  0.4835, -0.5983,  0.3013, -0.3221, -0.8970,
          0.1494, -0.1098, -0.6480, -0.7814],
        [-0.0670, -0.7207, -0.4550, -0.3116, -0.7561,  0.6989,  0.1072,  2.4627,
         -1.0210, -0.7791, -0.9551,  0.3421],
        [ 0.5550, -0.5904,  0.7705, -0.0333,  1.1292,  0.2469,  1.0940,  0.8088,
         -0.6790, -0.6639,  0.4363,  0.7201],
        [-0.2909, -0.1215,  0.4875, -1.3460, -0.6336,  0.8292, -0.3552,  0.3204,
         -0.1824,  1.8984, -0.1214,  1.0396]], requires_grad=True)
Parameter containing:
tensor([-1.6616,  2.0016, -0.6188, -0.3096,  0

## AutoGrad for Linear Regression


In [32]:
# y = 2x+1
import numpy as np
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
print(x_train.shape)
x_train = x_train.reshape(-1, 1)
print(x_train.shape)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)

(11,)
(11, 1)


In [33]:
(x_train, y_train)

(array([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]], dtype=float32), array([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.],
        [13.],
        [15.],
        [17.],
        [19.],
        [21.]], dtype=float32))

In [34]:
import torch
from torch.autograd import Variable
class LinearRegression(torch.nn.Module):
  def __init__(self, inputSize, outputSize):
    super(LinearRegression, self).__init__()
    self.linear = torch.nn.Linear(inputSize, outputSize)
  
  def forward(self,x ):
    out = self.linear(x)
    return out



In [44]:
inputDim = 1
outputDim = 1
learningRate = 0.01
epochs = 500

model = LinearRegression(inputDim, outputDim)
if torch.cuda.is_available():
  model.cuda()

In [45]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learningRate)


In [46]:
for epoch in range(epochs):
  if torch.cuda.is_available():
    inputs = Variable(torch.from_numpy(x_train).cuda())
    labels = Variable(torch.from_numpy(y_train).cuda())
  else:
    inputs = Variable(torch.from_numpy(x_train))
    labels = Variable(torch.from_numpy(y_train))

  optimizer.zero_grad()

  outputs =model(inputs)

  loss = criterion(outputs, labels)
  loss.backward()

  optimizer.step()

  print('epoch {}, lost {}'.format(epoch, loss.item()))

epoch 0, lost 249.11289978027344
epoch 1, lost 20.911090850830078
epoch 2, lost 2.2907984256744385
epoch 3, lost 0.7654640674591064
epoch 4, lost 0.6345862746238708
epoch 5, lost 0.6175217032432556
epoch 6, lost 0.6098124980926514
epoch 7, lost 0.6029360890388489
epoch 8, lost 0.5961978435516357
epoch 9, lost 0.589539647102356
epoch 10, lost 0.5829558968544006
epoch 11, lost 0.5764467120170593
epoch 12, lost 0.5700092911720276
epoch 13, lost 0.5636443495750427
epoch 14, lost 0.5573499798774719
epoch 15, lost 0.5511265397071838
epoch 16, lost 0.5449715852737427
epoch 17, lost 0.5388862490653992
epoch 18, lost 0.5328688025474548
epoch 19, lost 0.5269181132316589
epoch 20, lost 0.5210338830947876
epoch 21, lost 0.5152156352996826
epoch 22, lost 0.5094623565673828
epoch 23, lost 0.5037736296653748
epoch 24, lost 0.4981479346752167
epoch 25, lost 0.49258509278297424
epoch 26, lost 0.48708435893058777
epoch 27, lost 0.48164528608322144
epoch 28, lost 0.4762669503688812
epoch 29, lost 0.47094

In [49]:
with torch.no_grad():
  predicted = model(Variable(torch.from_numpy(x_train))).data.numpy()
  print(predicted)

[[ 0.9088082]
 [ 2.9219408]
 [ 4.9350734]
 [ 6.948206 ]
 [ 8.961338 ]
 [10.97447  ]
 [12.987603 ]
 [15.000736 ]
 [17.013868 ]
 [19.027    ]
 [21.040133 ]]




> 들여쓴 블록

