<a href="https://colab.research.google.com/github/gabrielwithappy/pytorch_references/blob/main/Pytorch_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# Pytorch 기본

## Tensor 생성

In [ ]:
data = [[3,5],[10,5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [ ]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

## GPU에 변수 올리기

In [ ]:
data = [[3,5],[10,5]]
x_data = torch.tensor(data)
x_data.device


device(type='cpu')

In [ ]:

if torch.cuda.is_available():
  x_data_cuda = x_data.to('cuda')
x_data_cuda.device

device(type='cuda', index=0)

## Torch View Hangling

In [ ]:
tensor_ex = torch.rand(size=(2, 3, 2))
tensor_ex

tensor([[[0.6075, 0.2419],
         [0.3252, 0.4242],
         [0.9686, 0.3278]],

        [[0.3841, 0.3731],
         [0.4988, 0.2533],
         [0.6208, 0.7282]]])

In [ ]:
tensor_ex.view([-1,6])

tensor([[0.6075, 0.2419, 0.3252, 0.4242, 0.9686, 0.3278],
        [0.3841, 0.3731, 0.4988, 0.2533, 0.6208, 0.7282]])

In [ ]:
tensor_ex.reshape([-1,6])

tensor([[0.6075, 0.2419, 0.3252, 0.4242, 0.9686, 0.3278],
        [0.3841, 0.3731, 0.4988, 0.2533, 0.6208, 0.7282]])

## Difference btw view and reshape

In [ ]:
a = torch.zeros(3,2)
b = a.view(2,3)
a.fill_(1)
# view를 사용하면 a의 메모리 주소를 이용하여 변경하기 때문에 a를 변경하면 view를 통해 변경한 b도 변경된다.

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## squeeze, unsqueeze

In [ ]:
tensor_ex = torch.rand(size=(2,1,2,3,4,5))
print(tensor_ex.shape)
tensor_ex = tensor_ex.squeeze()
print(tensor_ex.shape)

torch.Size([2, 1, 2, 3, 4, 5])
torch.Size([2, 2, 3, 4, 5])


In [ ]:
tensor_ex = torch.rand(size=(2,2))
print(tensor_ex.unsqueeze(0).shape)
print(tensor_ex.unsqueeze(1).shape)
print(tensor_ex.unsqueeze(2).shape)


torch.Size([1, 2, 2])
torch.Size([2, 1, 2])
torch.Size([2, 2, 1])


## Tensor Operation

In [ ]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

## matrix multiplication

In [ ]:
mat_result = t1.matmul(t2)
mat_result

tensor([[ 60.,  70.],
        [160., 195.]])

In [ ]:
t1.dot(t2)

RuntimeError: ignored

In [ ]:
## matmul 과 mul의 차이점
# matmul은 broadcasting을 지원한다.
# mul은 element-wise 곱셈
a = torch.rand(5,2,3)
b = torch.rand(3)
a.mm(b)

RuntimeError: ignored

## Tensor vs Parameter

In [ ]:
import torch
from torch import nn
from torch import Tensor

In [ ]:
class MyLinear(nn.Module):
  def __init__(self, in_features, out_features, bias=True):
    super().__init__()
    self.in_features = in_features
    self.out_features = out_features
    
    self.weights = nn.Parameter(
        torch.randn(in_features, out_features)
    )

    self.bias = nn.Parameter(torch.randn(out_features))

  def forward(self, x:Tensor):
    return x @ self.weights + self.bias

In [ ]:
x = torch.randn(5,7)

In [ ]:
x.shape

torch.Size([5, 7])

In [ ]:
layer = MyLinear(7,12)
layer(x).shape

torch.Size([5, 12])

In [ ]:
for value in layer.parameters():
  print(value)

Parameter containing:
tensor([[ 9.7292e-01,  7.2463e-01,  2.3686e+00,  1.0789e+00, -1.8030e-01,
          1.7170e+00, -2.9189e-01, -6.3930e-01,  2.3767e+00, -4.8461e-01,
         -1.1455e+00,  9.8930e-02],
        [-3.0441e-01, -1.1291e+00,  9.0228e-01, -4.0248e-01, -1.5091e-01,
         -1.6510e+00,  3.5810e-01, -2.3164e+00, -6.6426e-01, -8.0197e-01,
          4.5749e-01,  3.9867e-01],
        [ 1.9872e-02,  2.2586e-01,  1.6252e+00,  3.1897e-01, -8.0338e-01,
          6.6270e-01,  1.7231e+00, -1.1990e+00, -2.5709e-03,  1.0823e+00,
          1.2414e-01,  9.9336e-01],
        [ 2.0788e+00, -1.2982e+00, -5.8055e-01,  2.2683e+00,  1.3063e+00,
         -3.8147e-02,  5.3494e-01, -2.1415e+00, -5.5401e-01, -4.3145e-01,
         -1.8669e+00,  1.0214e+00],
        [-2.0151e-01, -1.2663e+00, -2.8822e-01,  4.1443e-01,  2.7657e-01,
          1.0840e+00, -1.0306e+00, -5.2982e-02, -1.2685e+00, -2.0949e+00,
         -1.2050e+00,  5.7478e-01],
        [ 4.1895e-01,  5.7040e-01, -2.2218e+00,  2.5730e+0